mode: test
task-name: JointFormer-PCBv2.2-occduke-pcb_vit_part-all
gpu: [0,1]


model-manager:
  network_name: jointformer_pcb_v2 # the network model
  save_name: jointformer_pcb_v2.2_pcb_vit_part-all
  load_path: True
  re_ranking: False
  metric: cosine
  network-params: # the params used to create model
    vit_pretrained_path: ./pretrained/jx_vit_base_p16_224-80ecf9dd.pth
    pretrained: True
    feature_mode: pcb_vit_part
    use_heatmap: False
    parts: 192
  network_inputs: ['img','heatmap'] # the data dict keys which the network input
  epoch: 300
  solver:
    optimizer: AdamW
    base_lr: 0.0001
    bias_lr_factor: 2
    cosine_mergin: 0.5
    weight_decay: 0.0001
    weight_decay_bias: 0.0001
    warmup_epochs: 10
    max_epoch: 500
  loss:
    use_loss: [cross_entropy, wrt]    # loss used for backward
    triplet:
      weight: 1
      list_weight: [1, 1, 0.5, 0.2, 0.2]
      #list_weight: [1, 0, 0]
    cross_entropy:
      weight: 1
      list_weight: [1, 1, 0.5, 0.2, 0.2] # for output score is list
    wrt:    # loss wrt params
      weight: 1     # loss weight in total loss
      except_input: 'feature'     # except input tensor type
      list_weight: [1, 1, 0.5, 0.2, 0.2]
    xent_label_smooth:     # loss xent_label_smooth params
      weight: 1.0
      params_initial: ['num_classes']     # params used for initialize the loss object
      except_input: 'score'       # except input tensor type


dataset:
  dataset_name: duke
  dataset_path: ../dataset/Occluded-DukeMTMC
  image_size:
    - 384
    - 128
  num_workers: 8
  batch_size_train: 160
  batch_size_test: 512
  type: image


