mode: test
task-name: TransReID-Duke
gpu: [0]


model-manager:
  network_name: transreid # the network model
  save_name: TransReID-Duke
  load_path: ./output/TransReID-Duke_120.pkl
  network-params: # the params used to create model
    PRETRAIN_CHOICE: 'imagenet'
    PRETRAIN_PATH: './pretrained/jx_vit_base_p16_224-80ecf9dd.pth'
    METRIC_LOSS_TYPE: 'triplet'
    IF_LABELSMOOTH: 'off'
    IF_WITH_CENTER: 'no'
    NAME: 'transformer'
    NO_MARGIN: True
    TRANSFORMER_TYPE: 'vit_base_patch16_224_TransReID'
    STRIDE_SIZE: [ 12, 12 ]
    SIE_CAMERA: True
    SIE_COE: 3.0
    JPM: True
    RE_ARRANGE: True
    CAMERA_NUM: 12
    SIZE_INPUT: [256, 128]
  network_inputs: ['img','camera_id'] # the data dict keys which the network input
  epoch: 120
  solver:
    optimizer: SGD
    base_lr: 0.008
    bias_lr_factor: 2
    cosine_mergin: 0.5
    weight_decay: 0.0001
    weight_decay_bias: 0.0001
    warmup_epochs: 5
    max_epoch: 120
    bias_lr_factor: 2
  loss:
    use_loss: ['cross_entropy','triplet']
    triplet:
      weight: 1.0
      list_weight: [0.5,0.125,0.125,0.125,0.125]  # for output feature is list
    cross_entropy:
      weight: 1.0
      list_weight: [0.5,0.125,0.125,0.125,0.125] # for output score is list
      except_input: 'score'
  re_ranking: False


dataset:
  dataset_name: duke
  dataset_path: ../dataset/DukeMTMC-reID
  image_size:
    - 256
    - 128
  num_workers: 8
  batch_size_train: 64
  batch_size_test: 256
  type: image


