mode: train
task-name: JointFormer-v0.5-duke

dataset:
  dataset_name: duke
  dataset_path: ../dataset/DukeMTMC-reID
  image_size:
    - 256
    - 128
  num_workers: 8
  batch_size_train: 64
  batch_size_test: 128
  type: image
