mode: train
task-name: JointFormer-PCBv2.2-occduke-vit_cls-all-l2_100
gpu: [0,1]


model-manager:
  network_name: jointformer_pcb_v2 # the network model
  save_name: jointformer_pcb_v2.2_vit_cls-all
  re_ranking: True
  metric: cosine
  network-params: # the params used to create model
    vit_pretrained_path: ./pretrained/jx_vit_base_p16_224-80ecf9dd.pth
    pretrained: True
    feature_mode: vit_cls
    use_heatmap: False
    parts: 192
    l2_norm: True
    mold: 200
  network_inputs: ['img','heatmap'] # the data dict keys which the network input
  epoch: 200
  solver:
    optimizer: AdamW
    base_lr: 0.0001
    bias_lr_factor: 1
    cosine_mergin: 0.5
    weight_decay: 0.0001
    weight_decay_bias: 0.0001
    warmup_epochs: 10
    max_epoch: 200
  loss:
    use_loss: [cross_entropy, triplet]    # loss used for backward
    triplet:
      weight: 1
      list_weight: [1, 1, 0.5, 0.2, 0.2]
      #list_weight: [1, 0, 0]
    cross_entropy:
      weight: 1
      list_weight: [1, 1, 0.5, 0.2, 0.2] # for output score is list
    wrt:    # loss wrt params
      weight: 1     # loss weight in total loss
      except_input: 'feature'     # except input tensor type
      list_weight: [1, 1, 0.5, 0.2, 0.2]
    xent_label_smooth:     # loss xent_label_smooth params
      weight: 1.0
      params_initial: ['num_classes']     # params used for initialize the loss object
      except_input: 'score'       # except input tensor type


dataset:
  dataset_name: duke
  dataset_path: ../dataset/Occluded-DukeMTMC
  num_workers: 8
  batch_size_train: 128
  batch_size_test: 256
  type: image
  reading_method_train:
    name: get_img_heatmap
    # define other parameter, such as image size
    image_size: [384, 128]
  reading_method_test:
    name: get_img_heatmap
    # define other parameter, such as image size
    image_size: [384, 128]

vis_params: # vis in tensorboardx
  vis: False       # visualize feature distribution
  vis_interval: 20  # visualization each [vis_interval]
  vis_img_func: list_false  # support: random, list_false, all
  vis_img_num: 100          # only valid in vis_img_func = random
