mode: train_test
gpu: [0]
task-name: JointFormer-v0.3-duke

network-params:
  name: JointFormer-v0.3-duke
  lr: 0.0001
  weight_decay: 0.0003
  epoch: 120
  continue_train: False
  optimzer: Adam
  vit-pretrained-path: ./pretrained/jx_vit_base_p16_224-80ecf9dd.pth
  camera-num: 15
  re_ranking: True
  mask_embed: True

dataset:
  dataset_name: duke
  dataset_path: ../dataset/DukeMTMC-reID
  image_size:
    - 384
    - 128
  num_workers: 8
  batch_size: 64
  type: image
