mode: train
task-name: JointFormer-v0.5-duke


model-manager:
  network_name: jointformer # the network model
dataset:
  dataset_name: duke
  dataset_path: ../dataset/DukeMTMC-reID
  image_size:
    - 256
    - 128
  num_workers: 8
  batch_size_train: 16
  batch_size_test: 32
  type: image
