mode: train_test
gpu: [0]
task-name: MaskFormer-v1-msmt17

network-params:
  name: MaskFormer-v1-msmt17
  lr: 0.00001
  weight_decay: 0.0003
  epoch: 64
  continue_train: False
  optimzer: SGD
  vit-pretrained-path: ./pretrained/jx_vit_base_p16_224-80ecf9dd.pth

dataset:
  dataset_name: msmt17
  dataset_path: ../dataset/MSMT17
  image_size:
    - 256
    - 128
  num_workers: 8
  batch_size: 64
  type: image
