mode: train
task-name: JointFormer-v0.5.5-duke
gpu: [1]


model-manager:
  network_name: jointformer # the network model
  save_name: JointFormer-v0.5.5
  network-params: # the params used to create model
    vit_pretrained_path: ./pretrained/jx_vit_base_p16_224-80ecf9dd.pth
  network_inputs: ['img','heatmap'] # the data dict keys which the network input
  epoch: 120
  solver:
    optimizer: SGD
    base_lr: 0.008
    bias_lr_factor: 2
    cosine_mergin: 0.5
    weight_decay: 0.0001
    weight_decay_bias: 0.0001
    warmup_epochs: 5
    max_epoch: 120
  loss:
    use_loss: ['cross_entropy','triplet']
    triplet:
      weight: 0.01
      list_weight: [0.3,0.1,0.1,0.1,0.3]
    cross_entropy:
      weight: 0.99
      list_weight: [0.3,0.1,0.1,0.1,0.3]


dataset:
  dataset_name: duke
  dataset_path: ../dataset/DukeMTMC-reID
  image_size:
    - 256
    - 128
  num_workers: 8
  batch_size_train: 128
  batch_size_test: 128
  type: image


