mode: test
task-name: JointFormer-v0.5.3-duke


model-manager:
  network_name: jointformer # the network model
  save_name: JointFormer-v0.5.3
  network_inputs: ['img','heatmap'] # the data dict keys which the network input
  epoch: 500
  solver:
    optimizer: Adam
    base_lr: 0.001
    weight_decay: 0.0003
    warmup_epochs: 10
    max_epoch: 500
  loss:
    use_loss: ['wrt','xent_label_smooth']    # loss used for backward
    wrt:
      weight: 0.01
    xent_label_smooth:
      weight: 0.99


dataset:
  dataset_name: duke
  dataset_path: ../dataset/DukeMTMC-reID
  image_size:
    - 256
    - 128
  num_workers: 8
  batch_size_train: 64
  batch_size_test: 64
  type: image


