mode: train_test
gpu: [0]
task-name: MaskFormer-v1-ltcc

network-params:
  name: MaskFormer-v1-ltcc-2
  lr: 0.00001
  weight_decay: 0.0003
  epoch: 64
  continue_train: True
  optimzer: SGD
  vit-pretrained-path: ./pretrained/jx_vit_base_p16_224-80ecf9dd.pth

dataset:
  dataset_name: ltcc
  dataset_path: ../dataset/LTCC_ReID
  image_size:
    - 256
    - 128
  num_workers: 8
  batch_size: 64
  seq_len: 30
  type: image
