mode: train
gpu: [0]
task-name: MaskFormer-v1-msmt17
eval_interval: 20 # eval each [eval_interval]
vis: True       # visualize feature distribution
vis_interval: 20  # visualization each [vis_interval]

network-params:
  name: MaskFormer-v1-msmt17-Adam
  lr: 0.1
  lr-adjust:
    - 10
    - 30
    - 100
  weight_decay: 0.0003
  epoch: 128
  continue_train: False
  optimzer: Adam
  vit-pretrained-path: ./pretrained/jx_vit_base_p16_224-80ecf9dd.pth
  camera-num: 15
  re_ranking: False
  mask_embed: True

dataset:
  dataset_name: msmt17
  dataset_path: ../dataset/MSMT17
  image_size:
    - 256
    - 128
  num_workers: 8
  batch_size: 64
  type: image
