mode: train
task-name: JointFormer-PCB-duke
gpu: [0]


model-manager:
  network_name: jointformer_pcb # the network model
  save_name: jointformer_pcb
  network-params: # the params used to create model
    vit_pretrained_path: ./pretrained/jx_vit_base_p16_224-80ecf9dd.pth
    pretrained: True
  network_inputs: ['img','heatmap'] # the data dict keys which the network input
  epoch: 120
  solver:
    optimizer: Adam
    base_lr: 0.0001
    bias_lr_factor: 2
    cosine_mergin: 0.5
    weight_decay: 0.0001
    weight_decay_bias: 0.0001
    warmup_epochs: 5
    max_epoch: 120
  loss:
    use_loss: ['cross_entropy','triplet']
    triplet:
      weight: 0.01
    cross_entropy:
      weight: 0.99
      list_weight: [0.75,0.25] # for output score is list


dataset:
  dataset_name: duke
  dataset_path: ../dataset/DukeMTMC-reID
  image_size:
    - 384
    - 128
  num_workers: 8
  batch_size_train: 64
  batch_size_test: 128
  type: image


