mode: train
gpu: [0]
task-name: MaskFormer-v1-ltcc
eval_interval: 20 # eval each [eval_interval]
vis: True       # visualize feature distribution
vis_interval: 20  # visualization each [vis_interval]

network-params:
  name: MaskFormer-v1-ltcc-2
  lr: 0.0001
  weight_decay: 0.0003
  epoch: 1024
  continue_train: True
  optimzer: SGD
  vit-pretrained-path: ./pretrained/jx_vit_base_p16_224-80ecf9dd.pth
  camera-num: 12
  re_ranking: True

dataset:
  dataset_name: ltcc
  dataset_path: ../dataset/LTCC_ReID
  image_size:
    - 256
    - 128
  num_workers: 8
  batch_size: 32
  type: image
