mode: train
gpu: [0]
task-name: MaskFormer-v1-msmt17-no_mask

network-params:
  name: MaskFormer-v1-msmt17-no_mask
  lr: 0.001
  weight_decay: 0.0003
  epoch: 128
  continue_train: True
  optimzer: Adam
  vit-pretrained-path: ./pretrained/jx_vit_base_p16_224-80ecf9dd.pth
  camera-num: 15
  re_ranking: False
  mask_embed: False

dataset:
  dataset_name: msmt17
  dataset_path: ../dataset/MSMT17
  image_size:
    - 256
    - 128
  num_workers: 8
  batch_size: 64
  type: image
