mode: train
task-name: JointFormer-v0.5.4-duke


model-manager:
  network_name: jointformer # the network model
  save_name: JointFormer-v0.5.4
  network_inputs: ['img','heatmap'] # the data dict keys which the network input
  epoch: 120
  solver:
    optimizer: Adam
    base_lr: 0.008
    weight_decay: 0.0001
    weight_decay_bias: 0.0001
    warmup_epochs: 10
    max_epoch: 120
    bias_lr_factor: 2
  loss:
    use_loss: ['cross_entropy','triplet']
    triplet:
      weight: 0.01
    cross_entropy:
      weight: 0.99
      list_weight: [0.75,0.25] # for output score is list


dataset:
  dataset_name: duke
  dataset_path: ../dataset/DukeMTMC-reID
  image_size:
    - 256
    - 128
  num_workers: 8
  batch_size_train: 128
  batch_size_test: 128
  type: image


