mode: train
task-name: JointFormerV0.6-duke-pretrained
gpu: [0]


model-manager:
  network_name: jointformerv0.6 # the network model
  save_name: jointformerv0_6
  network-params: # the params used to create model
    vit_pretrained_path: ./pretrained/jx_vit_base_p16_224-80ecf9dd.pth
    pretrained: True
  network_inputs: ['img','heatmap'] # the data dict keys which the network input
  epoch: 120
  solver:
    optimizer: Adam
    base_lr: 0.0001
    bias_lr_factor: 2
    cosine_mergin: 0.5
    weight_decay: 0.0001
    weight_decay_bias: 0.0001
    warmup_epochs: 5
    max_epoch: 120
  loss:
    use_loss: [cross_entropy]    # loss used for backward
    triplet:
      weight: 0.01
      #list_weight: [1, 0, 0]
    cross_entropy:
      weight: 0.995
      list_weight: [1, 1, 0.5, 0.2, 0.2] # for output score is list
    wrt:    # loss wrt params
      weight: 0.001     # loss weight in total loss
      except_input: 'feature'     # except input tensor type
    xent_label_smooth:     # loss xent_label_smooth params
      weight: 1.0
      params_initial: ['num_classes']     # params used for initialize the loss object
      except_input: 'score'       # except input tensor type


dataset:
  dataset_name: duke
  dataset_path: ../dataset/DukeMTMC-reID
  image_size:
    - 384
    - 128
  num_workers: 8
  batch_size_train: 4
  batch_size_test: 128
  type: image


