mode: train
gpu: [0]
eval_interval: 20 # eval each [eval_interval]
vis: True       # visualize feature distribution
vis_interval: 20  # visualization each [vis_interval]

network-params:
  name: network-msmt17
  lr: 0.0001
  lr_adjust:
    - 20
    - 40
    - 60
    - 90
  weight_decay: 0.0003
  epoch: 128
  continue_train: False
  optimzer: Adam
  re_ranking: False

dataset:
  dataset_name: msmt17
  dataset_path: ../dataset/MSMT17
  image_size:
    - 256
    - 128
  num_workers: 8
  batch_size: 4
  seq_len: 30
  type: image
  num-mask: 6
