mode: test
vis: True       # visualize feature distribution
vis_interval: 20  # visualization each [vis_interval]

dataset:
  dataset_name: duke
  dataset_path: ../dataset/DukeMTMC-reID
  num_workers: 8
  batch_size_train: 64
  batch_size_test: 128
  type: image
  # reading method
  reading_method_train:
    name: get_img_hm
    # define other parameter, such as image size
    image_size: [256, 128]
  reading_method_test:
    name: get_img_hm
    # define other parameter, such as image size
    image_size: [256, 128]


vis_params: # vis in tensorboardx
  vis: True       # visualize feature distribution
  vis_interval: 20  # visualization each [vis_interval]
  vis_img_func: all  # support: random, list_false, all
  vis_img_num: 100          # only valid in vis_img_func = random