mode: train
gpu: [0]



network-params:
  name: network-mars
  lr: 0.00035
  lr_adjust:
    - 20
    - 40
    - 60
    - 90
  weight_decay: 0.0005
  epoch: 64
  continue_train: true
  optimzer: Adam

dataset:
  dataset_name: mars
  dataset_path: ../DATASET/mars
  image_size:
    - 256
    - 128
  num_workers: 8
  batch_size: 2
  seq_len: 30
  type: video
  num-mask: 5
