mode: train
gpu: [0]
eval_interval: 20 # eval each [eval_interval]
vis: True       # visualize feature distribution
vis_interval: 20  # visualization each [vis_interval]


network-params:
  name: network-market
  lr: 0.0001
  lr_adjust:
    - 20
    - 40
    - 60
    - 90
  weight_decay: 0.0003
  epoch: 64
  continue_train: True
  optimzer: Adam
  re_ranking: True

dataset:
  dataset_name: market
  dataset_path: ../dataset/market1501
  image_size:
    - 256
    - 128
  num_workers: 8
  batch_size: 32
  type: image
