gpu: [0]
eval_interval: 10 # eval each [eval_interval]
task-name: transformer-occ_duke

model-manager:
  network_name: transformer # the network model
  network-params: # the params used to create model
    pretrained: ./pretrained/jx_vit_base_p16_224-80ecf9dd.pth
    img_size: [256,128]
    num_camera: 11
  network_inputs: ['img', 'camera_id'] # the data dict keys which the network input
  save_name: model  # final model save name is [save_name]_[epoch].pkl
  #load_path: ./output/test.pkl   # load from './output/test.pkl'
  #load_path: True        # auto load model with [save_name]
  #load_path: False       # Do Not Load
  epoch: 128
  solver:
    optimizer: SGD
    base_lr: 0.008
    weight_decay: 0.0003
    warmup_epochs: 5
    max_epoch: 120
  loss:
    use_loss: ['xent_label_smooth','wrt']    # loss used for backward
    wrt:    # loss wrt params
      weight: 1.0     # loss weight in total loss
      except_input: 'feature'     # except input tensor type
      list_weight: [0.5, 0.125, 0.125, 0.125, 0.125]
    xent_label_smooth:     # loss xent_label_smooth params
      weight: 1.0
      params_initial: ['num_classes']     # params used for initialize the loss object
      except_input: 'score'       # except input tensor type
      list_weight: [0.5, 0.125, 0.125, 0.125, 0.125]
    triplet:
      weight: 1.0
      except_input: 'feature'
      list_weight: [0.5, 0.125, 0.125, 0.125, 0.125]
    cross_entropy:
      weight: 1.0
      except_input: 'score'       # except input tensor type
      list_weight: [0.5, 0.125, 0.125, 0.125, 0.125]
  # use for visulize feature distribution
  # vis_pid_[test/train] can be int or list
  # int: random select [vis_pid_train/test] pids' samples for visualization
  # list: select pids' samples which in [vis_pid_train/test] list for visualization
  vis_pid_train: 30
  vis_pid_test: 30

dataset:
  dataset_name: duke
  dataset_path: ../dataset/Occluded-DukeMTMC
  image_size:
    - 256
    - 128
  num_workers: 8
  batch_size_train: 64
  batch_size_test: 128
  num_instance: 8
  type: image
  # reading method
  reading_method_train:
    name: get_img
    # define other parameter, such as image size
    type: train
    image_size: [256, 128]
  reading_method_test:
    name: get_img
    # define other parameter, such as image size
    type: test
    image_size: [256, 128]

vis_params: # vis in tensorboardx
  vis: False       # visualize feature distribution
  vis_interval: 20  # visualization each [vis_interval]
  vis_img_func: list_false  # support: random, list_false, all
  vis_img_num: 100          # only valid in vis_img_func = random
